/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Calculator */

#ifndef _Included_jni_Calculator
#define _Included_jni_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Calculator
 * Method:    calculate
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_Calculator_calculate
  (JNIEnv *, jobject, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
